name: "Docker Stack Deploy"
description: "Deploy a Docker Stack"
author: "Shane"
branding:
  icon: "layers"
  color: "green"

inputs:
  host:
    description: "Docker Host"
    required: true
  port:
    description: "Docker Port"
    default: "22"
    required: false
  user:
    description: "Docker User"
    required: true
  pass:
    description: "Docker Pass"
    required: false
  ssh_key:
    description: "SSH Key File"
    required: false
  file:
    description: "Docker Compose File"
    default: "docker-compose.yaml"
    required: false
  name:
    description: "Docker Stack Name"
    required: true
  env_file:
    description: "Environment File"
    required: false
  docker_user:
    description: "Docker User for Login in Private registry"
    required: true
  docker_password:
    description: "Docker User Password"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
